# Generated by Django 5.1.3 on 2024-11-24 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('link', models.CharField(max_length=100)),
                ('post', models.CharField(max_length=2000)),
                ('date', models.DateField(verbose_name='Published on: ')),
                ('tags', models.CharField(max_length=100)),
            ],
        ),
    ]
